### ISSUE TITLE
Packages fail to load because of redirect to http://server.com/public, not http://server.com/exist/apps/public-repo/public

### ISSUE THREAD

**Issue by brobertson** [eXist-db/public-repo#49]
When directed to a v. 1.0.3 public-repo, the  packagemanager claims it has loaded, but error messages in the log read like this:

```
> 2019-11-30 14:10:39,374 [qtp1176909502-4635] INFO  (Deploy.java [load]:297) - Retrieving package from http://192.168.2.21:8080/exist/apps/public-repo//modules/find.xql?name=http%3A%2F%2Fheml.mta.ca%2FLace%2FImages%2Factaphilippietac00bonnuoft&processor=5.1.0&version=1 
> 2019-11-30 14:10:39,500 [qtp1176909502-4635] ERROR (Deploy.java [installAndDeploy]:214) - Failed to install dependency from http://192.168.2.21:8080/exist/apps/public-repo//modules/find.xql?name=http%3A%2F%2Fheml.mta.ca%2FLace%2FImages%2Factaphilippietac00bonnuoft&processor=5.1.0&version=1: http://192.168.2.21:8080/public/actaphilippietac00bonnuoft-images.xar 
> java.io.IOException: Failed to install dependency from http://192.168.2.21:8080/exist/apps/public-repo//modules/find.xql?name=http%3A%2F%2Fheml.mta.ca%2FLace%2FImages%2Factaphilippietac00bonnuoft&processor=5.1.0&version=1: http://192.168.2.21:8080/public/actaphilippietac00bonnuoft-images.xar
> 	at org.exist.xquery.modules.expathrepo.Deploy$RepoPackageLoader.load(Deploy.java:313) ~[exist-expathrepo-5.1.0.jar:5.1.0]
> 	at org.exist.xquery.modules.expathrepo.Deploy.installAndDeploy(Deploy.java:206) ~[exist-expathrepo-5.1.0.jar:5.1.0]
> 	at org.exist.xquery.modules.expathrepo.Deploy.eval(Deploy.java:173) ~[exist-expathrepo-5.1.0.jar:5.1.0]
> 	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:74) ~[exist-core-5.1.0.jar:5.1.0]
```

Using curl shows that this is because of a bad redirect to `http://server.com/public`, not what I assume is correct, `http://server.com/exist/apps/public-repo/public`

```
> curl -v 'http://192.168.2.21:8080/exist/apps/public-repo//modules/find.xql?name=http%3A%2F%2Fheml.mta.ca%2FLace%2FImages%2Factaphilippietac00bonnuoft&processor=5.1.0&version=1'
> *   Trying 192.168.2.21...
> * TCP_NODELAY set
> * Connected to 192.168.2.21 (192.168.2.21) port 8080 (#0)
> > GET /exist/apps/public-repo//modules/find.xql?name=http%3A%2F%2Fheml.mta.ca%2FLace%2FImages%2Factaphilippietac00bonnuoft&processor=5.1.0&version=1 HTTP/1.1
> > Host: 192.168.2.21:8080
> > User-Agent: curl/7.64.1
> > Accept: */*
> >
> < HTTP/1.1 302 Found
> < Date: Sat, 30 Nov 2019 20:04:41 GMT
> < X-XQuery-Cached: true
> < Location: http://192.168.2.21:8080/public/actaphilippietac00bonnuoft-images.xar
> < Content-Length: 0
> < Server: Jetty(9.4.22.v20191022)
> <
> * Connection #0 to host 192.168.2.21 left intact
> * Closing connection 0
```

It seems that this is because the `$app-root-absolute-url` variable in find.xql is empty. It therefore is likely that the logic in controller.xql is at fault. It seems to assume that the endpoint is `find` (for which the `$app-root-absolute-url` is in fact passed), not `find.xql` (for which it apparently is not), 
but db/apps/packageservice/modules/apputil.xql l. 126 uses the endpoint `/modules/find.xql`

**Comment by joewiz** [comment]
@brobertson Indeed, I think I must not have considered the case of a public-repo being hosted at an IP address, rather than a domain name, in [my recent updates](https://github.com/eXist-db/public-repo/pull/48) to public-repo. I'll need to As to the `find` vs. `find.xql` endpoint, I've got a PR [updating packageservice to use `find`](https://github.com/eXist-db/existdb-packageservice/pull/12).

**Comment by brobertson** [comment]
Great! For what it's worth, this controller.xql works for me in the configuration I describe above:

```
xquery version "3.1";

import module namespace login="http://exist-db.org/xquery/login" at "resource:org/exist/xquery/modules/persistentlogin/login.xql";

declare variable $exist:path external;
declare variable $exist:resource external;
declare variable $exist:controller external;
declare variable $exist:prefix external;
declare variable $exist:root external;
    
declare variable $app-root-absolute-url := 
    (request:get-header("X-Forwarded-Proto"), request:get-scheme())[1] 
    || "://"
    || (request:get-header("X-Forwarded-Server"), request:get-server-name())[1]
    (: The server port was not included in the absolute URL, and so 
       : this code would not work with servers on ports other than 80. 
       : I've added it here 
     :)
    || ":" 
    || xs:string(request:get-server-port())
    || request:get-context-path()
    || $exist:prefix
    || $exist:controller
;


login:set-user("org.exist.public-repo.login", (), false()),

if ($exist:path eq "") then
    <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
        <redirect url="{request:get-uri()}/"/>
    </dispatch>

else if ($exist:path eq "/") then
    (: forward root path to index.xql :)
    <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
        <redirect url="index.html"/>
    </dispatch>

else if ($exist:path eq "/public/apps.xml") then (
    response:set-header('Content-Type', 'application/xml'),
    <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
        <forward url="{$exist:controller}/modules/list.xql"/>
    </dispatch>
)
else if ($exist:resource eq "update.xql") then
    <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
        <forward url="{$exist:controller}/modules/update.xql"/>
        <view>
            <forward url="{$exist:controller}/index.html"/>
            <forward url="{$exist:controller}/modules/view.xql">
                <set-header name="Cache-Control" value="no-cache"/>
            </forward>
        </view>
    </dispatch>
    
(:  Protected resource: user is required to log in with valid credentials.
    If the login fails or no credentials were provided, the request is redirected
    to the login.html page. :)
else if ($exist:path eq "/admin.html") then
    let $user := request:get-attribute("org.exist.public-repo.login.user")
    return
        if ($user and (sm:is-dba($user) or "repo" = sm:get-user-groups($user))) then
            <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
                <view>
                    <forward url="{$exist:controller}/modules/view.xql">
                        <set-header name="Cache-Control" value="no-cache"/>
                    </forward>
                </view>
            </dispatch>
        else
            <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
                <forward url="login.html"/>
                <view>
                    <forward url="{$exist:controller}/modules/view.xql">
                        <set-header name="Cache-Control" value="no-cache"/>
                    </forward>
                </view>
            </dispatch>

else if (ends-with($exist:resource, ".html") and starts-with($exist:path, "/packages")) then
    <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
        <forward url="{concat($exist:controller, '/packages.html')}"/>
        <view>
            <forward url="{concat($exist:controller, '/modules/view.xql')}">
                <add-parameter name="abbrev" value="{substring-before($exist:resource, '.html')}"/>
            </forward>
        </view>
    </dispatch>
    
else if (ends-with($exist:resource, ".html")) then
    (: the html page is run through view.xql to expand templates :)
    <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
        <view>
            <forward url="modules/view.xql">
                <set-header name="Cache-Control" value="no-cache"/>
            </forward>
        </view>
    </dispatch>

else if (contains($exist:path, "/public/") and ends-with($exist:resource, ".zip")) then
    <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
        <forward url="../modules/download-xar-zip.xq"/>
    </dispatch>

else if ($exist:path eq "/find" or ends-with($exist:resource, ".zip")) then
    <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
        <forward url="modules/find.xql">
            <add-parameter name="app-root-absolute-url" value="{$app-root-absolute-url}"/>
        </forward>
    </dispatch>

else if ($exist:resource eq "feed.xml") then
    <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
        <forward url="modules/feed.xql"/>
    </dispatch>

else if (contains($exist:path, "/$shared/")) then
    <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
        <forward url="/shared-resources/{substring-after($exist:path, '/$shared/')}">
            <set-header name="Cache-Control" value="max-age=3600, must-revalidate"/>
        </forward>
    </dispatch>

else if (contains($exist:path, "/resources/")) then
    <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
        <forward url="{$exist:controller}/resources/{substring-after($exist:path, '/resources/')}">
            <set-header name="Cache-Control" value="max-age=3600, must-revalidate"/>
        </forward>
    </dispatch>
    
else if (ends-with($exist:path, ".xml")) then
    <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
        <set-header name="Cache-Control" value="no-cache"/>
    </dispatch>

else
    (: everything else is passed through :)
    (: Passing the app-root-aboslute-url parameter to everything else 
     : ensures that find.xql receives it. 
    :)
    <dispatch xmlns="http://exist.sourceforge.net/NS/exist">
        <add-parameter name="app-root-absolute-url" value="{$app-root-absolute-url}"/>
        <cache-control cache="yes"/>
    </dispatch>
```

**Comment by joewiz** [comment]
@brobertson Thanks! Would you consider submitting a PR?

**Comment by brobertson** [comment]
I'm not sure I should, because this is a bit of a blunt instrument approach I'm taking here. You'll note that I pass the app-root-absolute-url parameter to 'everything else' so that I know that find.xql will catch it, but your pr will limit that to 'find'. At very least, perhaps I'll ask you to check that it works for everything you're doing before making the pr.

**Comment by brobertson** [comment]
@joewiz . I think we do need this to be working one way or another. If I submit the above controller in a PR, could you test on your proxying scenario? I'm just not confident that I've fully understood the code.

**Comment by joewiz** [comment]
@brobertson Sorry for the delay on addressing this. I think I've found a fix, which is part of a larger PR: https://github.com/eXist-db/public-repo/pull/53/commits/d7bc1783e8491d1789c886d1882ad23f45ede516#diff-be7412746393b18ae23052e25cbb0ffb12fd8a007c659241956de4082ab1b775.
